apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "aegis.fullname" . }}-conf
  labels:
    {{- include "aegis.labels" . | nindent 4 }}
data:
  config.json: |-
    {{- toJson $.Values.config | nindent 4 }}  